src/SFA.DAS.ApplyService.Web/ViewModels/SequenceViewModel.cs
using System;
using System.Collections.Generic;
using SFA.DAS.ApplyService.Domain.Apply;
using SFA.DAS.ApplyService.Domain.Entities;

namespace SFA.DAS.ApplyService.Web.ViewModels
{
    public class SequenceViewModel
    {
        public SequenceViewModel(ApplicationSequence sequence, Guid applicationId, List<ValidationErrorDetail> errorMessages)
        {
            ApplicationId = applicationId;
            Sections = sequence.Sections;
            SequenceId = (int)sequence.SequenceId;
            Status = sequence.Status;
            ErrorMessages = errorMessages;
        }

        public string Status { get; }
        public List<ApplicationSection> Sections { get; }

        public Guid ApplicationId { get; }
        public int SequenceId { get; }
        public List<ValidationErrorDetail> ErrorMessages { get; }
    }
}

src/SFA.DAS.ApplyService.Web/Controllers/Roatp/ApplicationController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ApplyService.Web.Infrastructure;

namespace SFA.DAS.ApplyService.Web.Controllers.Roatp
{

    [Authorize]
    public class ApplicationController: Controller
    {
        private readonly IQnaApiClient _qnaApiClient;
        private readonly IApplicationApiClient _apiClient;

        public ApplicationController(IQnaApiClient qnaApiClient, IApplicationApiClient apiClient)
        {
            _qnaApiClient = qnaApiClient;
            _apiClient = apiClient;
        }

        public async Task<IActionResult> Download(Guid Id, int sequenceNo, int sectionId, string pageId, string questionId, string filename)
        {
            var selectedSection = await _qnaApiClient.GetSectionBySectionNo(Id, sequenceNo, sectionId);

            var response = await _qnaApiClient.DownloadFile(Id, selectedSection.Id, pageId, questionId, filename);
            var fileStream = await response.Content.ReadAsStreamAsync();

            return File(fileStream, response.Content.Headers.ContentType.MediaType, filename);

        }


        public async Task<IActionResult> DeleteFile(Guid Id, int sequenceNo, int sectionId, string pageId, string questionId, string filename, string __redirectAction)
        {
            var selectedSection = await _qnaApiClient.GetSectionBySectionNo(Id, sequenceNo, sectionId);

            await _qnaApiClient.DeleteFile(Id, selectedSection.Id, pageId, questionId, filename);

            return RedirectToAction("Page", "RoatpApplication", new { applicationId = Id, sequenceId = sequenceNo, sectionId, pageId, redirectAction = __redirectAction });
        }
    }
}

src/SFA.DAS.ApplyService.Web/Views/Application/Index.cshtml
@model List<SFA.DAS.ApplyService.Domain.Entities.Application>

@{
ViewBag.Title = "Applications";
}

<main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <!-- <h1 class="govuk-heading-xl">Signed in</h1> -->
            <h1 class="govuk-heading-xl">
                Select application
            </h1>
            <table class="govuk-table">
                <thead class="govuk-table__head">
                    <tr class="govuk-table__row">
                        <th class="govuk-table__header" scope="col">Application</th>
                        <!-- <th class="govuk-table__header" scope="col">Application ID</th> -->
                        <th class="govuk-table__header govuk-table__header--numeric" scope="col">Status</th>
                        <th class="govuk-table__header govuk-table__header--numeric" scope="col">Action</th>
                    </tr>
                </thead>
                <tbody class="govuk-table__body">

                    @foreach (var application in Model)
                    {
                    <tr>
                        <th class="govuk-table__header" scope="row">Not yet submitted</th>
                        <!-- <td class="govuk-table__cell">@application.Id</td> -->
                        <td class="govuk-table__cell govuk-table__cell--numeric">In progress</td>
                        <td class="govuk-table__cell govuk-table__cell--numeric">
                            <a href="@Url.Action("Sequences","Application", new {applicationId=application.Id, sequenceId = 1})">View</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</main>

src/SFA.DAS.ApplyService.Web/Views/Application/PagesWithSections.cshtml
@using SFA.DAS.ApplyService.Web.ViewModels.Roatp
@model SFA.DAS.ApplyService.Domain.Entities.ApplicationSection
@using SFA.DAS.ApplyService.Domain.Entities
@{
    ViewBag.Title = @Model.Title;
    Layout = "_Layout";
    var pageTitle = "";
    var nextPageTitle = "";
    var pagesToCheck = Model.QnAData.Pages.Where(p => p.Active && !p.NotRequired && p.DisplayType!=null && p.DisplayType == PageDisplayType.PagesWithSections).ToList();
    var pageId = pagesToCheck?.FirstOrDefault()?.PageId;
}

<partial name="~/Views/Roatp/ApplicationHeader.cshtml" />

@*<a class="govuk-back-link" asp-action="Back" asp-controller="RoatpApplication" asp-route-applicationId="@Model.ApplicationId" asp-route-sequenceId="@Model.SequenceId" asp-route-sectionId="@Model.SectionId" asp-route-pageId="@pageId" asp-route-redirectAction="TaskList">Back</a>*@

<main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            @if (Model == null)
            {
                <h1 class="govuk-heading-xl">Section not active</h1>
            }
            else
            {
                <h1 class="govuk-heading-xl">@Model.Title</h1>

                <ol class="app-task-list">
                    <li>
                        <h2 class="app-task-list__section">@Html.Raw(pagesToCheck[0].Title)</h2>
                        <ul class="app-task-list__items app-task-list__items--no-number">
                            @for (var i = 0; i < pagesToCheck.Count; i++)
                            {
                                var pg = pagesToCheck[i];
                                pageTitle = pg.Title;
                                nextPageTitle = "";

                                if (i < pagesToCheck.Count - 1)
                                {
                                    nextPageTitle = (pagesToCheck[i + 1]).Title;
                                }

                                <li class="app-task-list__item">
                                    <span class="app-task-list__task-name">
                                        <a
                                            class="govuk-link"
                                            asp-action="Page"
                                            asp-controller="RoatpApplication"
                                            asp-route-applicationId="@Model.ApplicationId"
                                            asp-route-sequenceId="@Model.SequenceId"
                                            asp-route-sectionId="@Model.SectionId"
                                            asp-route-pageId="@pg.PageId"
                                            asp-route-redirectAction="Section"
                                        >
                                            @pg.LinkTitle
                                        </a>
                                    </span>

                                    @if (pg.StatusText== TaskListSectionStatus.Completed)
                                    {
                                        <strong class="govuk-tag app-task-list__task-completed" id="completed">Completed</strong>
                                    }
                                    
                                    @if (pg.StatusText == TaskListSectionStatus.InProgress)
                                    {
                                        <strong class="govuk-tag app-task-list__task-inprogress" id="inprogress">In progress</strong>
                                    }
                                </li>

                                @if (nextPageTitle != pageTitle)
                                {
                                    @Html.Raw("</ul></li>");
                                    if (i < pagesToCheck.Count - 1)
                                    {
                                        @Html.Raw("<li><h2 class=\"app-task-list__section\">")
                                        @nextPageTitle
                                        @Html.Raw("</h2><ul class=\"app-task-list__items app-task-list__items--no-number\">")
                                    }
                                }

                            }
                        </ul>
                    </li>
                </ol>
                <a class="govuk-button" asp-action="Tasklist" asp-controller="RoatpApplication" asp-route-applicationId="@Model.ApplicationId" asp-fragment="@($"Sequence_{Model.SequenceId}")">Go to application overview</a>
            }
        </div>
    </div>
</main>

src/SFA.DAS.ApplyService.Web/Views/Application/Section.cshtml
@model SFA.DAS.ApplyService.Domain.Entities.ApplicationSection

@{
    ViewBag.Title = @Model?.Title ?? "Section not active";
    Layout = "_Layout";
}

@*@if (Model == null)
{
    <a asp-action="Applications" asp-controller="Application" class="govuk-back-link">Back to application overview</a>
}
else
{
    <a asp-action="Sequence" asp-controller="Application" asp-route-applicationId="@Model.ApplicationId" class="govuk-back-link">Back to application overview</a>
}*@
<main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            @if (Model == null)
            {
                <h1 class="govuk-heading-xl">Section not active</h1>
            }
            else
            {
                <h1 class="govuk-heading-xl">@Model.Title</h1>
                <ol class="app-task-list">
                    <li>
                        <ul class="app-task-list__items app-task-list__items--no-number">
                            @foreach (var pg in Model.QnAData.Pages.Where(p => p.Active && !p.NotRequired))
                            {
                                <li class="app-task-list__item">
                                    <span class="app-task-list__task-name">
                                        <a
                                            class="govuk-link"
                                            asp-action="Page"
                                            asp-controller="Application"
                                            asp-route-applicationId="@Model.ApplicationId"
                                            asp-route-sequenceId="@Model.SequenceId"
                                            asp-route-sectionId="@Model.SectionId"
                                            asp-route-pageId="@pg.PageId"
                                            asp-route-redirectAction="Section"
                                        >
                                           @pg.LinkTitle
                                        </a>
                                    </span>
                                    @if (pg.Complete)
                                    {
                                        <strong class="govuk-tag app-task-list__task-completed" id="completed">Completed</strong>
                                    }
                                </li>
                            }
                        </ul>
                    </li>
                </ol>
                <a class="govuk-button" asp-action="Tasklist" asp-controller="RoatpApplication" asp-route-applicationId="@Model.ApplicationId" asp-fragment="@($"Sequence_{Model.SequenceId}")">Return to application overview</a>
            }
        </div>
    </div>
</main>

src/SFA.DAS.ApplyService.Web/Views/Application/SectionQuestions.cshtml
@model SFA.DAS.ApplyService.Domain.Entities.ApplicationSection

@{
    ViewBag.Title = @Model.Title;
    Layout = "_Layout";
}

@*<a asp-action="Sequence" asp-controller="Application" asp-route-applicationId="@Model.ApplicationId" class="govuk-back-link">Back to application overview</a>*@
<main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            @if (Model == null)
            {
                <h1 class="govuk-heading-xl">Sequence not active</h1>
            }
            else
            {
                <h1 class="govuk-heading-xl">@Model.Title</h1>

                <ol class="app-task-list">
                    @foreach (var pg in Model.QnAData.Pages.Where(p => p.Active && !p.NotRequired))
                    {
                        <li>
                            <h2 class="app-task-list__section">@Html.Raw(pg.Title)</h2>
                            <ul class="app-task-list__items app-task-list__items--no-number">
                                @foreach (var question in pg.Questions)
                                {
                                    <li class="app-task-list__item">
                                        <span class="app-task-list__task-name">
                                            <a
                                                class="govuk-link"
                                                asp-action="Page"
                                                asp-controller="Application"
                                                asp-route-applicationId="@Model.ApplicationId"
                                                asp-route-sequenceId="@Model.SequenceId"
                                                asp-route-sectionId="@Model.SectionId"
                                                asp-route-pageId="@pg.PageId"
                                                asp-route-redirectAction="Section"
                                            >
                                                @question.ShortLabel
                                            </a>
                                        </span>
                                        @if (pg.IsQuestionAnswered(question.QuestionId))
                                        {
                                            <strong class="govuk-tag app-task-list__task-completed" id="completed">Completed</strong>
                                        }
                                    </li>
                                }
                            </ul>
                        </li>
                    }
                </ol>
                <a class="govuk-button" asp-action="Tasklist" asp-controller="RoatpApplication" asp-route-applicationId="@Model.ApplicationId" asp-fragment="@($"Sequence_{Model.SequenceId}")">Return to application overview</a>
            }
        </div>
    </div>
</main>

src/SFA.DAS.ApplyService.Web/Views/Application/Sequence.cshtml
@using SFA.DAS.ApplyService.Domain.Entities
@model SFA.DAS.ApplyService.Web.ViewModels.SequenceViewModel

@{
    ViewBag.Title = "Application overview";
    Layout = "_Layout";
}

@* Commenting out the below until we actually need it.. will need logic if (applications > 1) {} *@
@* <a asp-action="Applications" asp-controller="Application" class="govuk-back-link">Back to application selection</a> *@
<main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            @if (!ViewData.ModelState.IsValid || Model.ErrorMessages?.Any() is true)
            {
                <div class="govuk-error-summary" aria-labelledby="error-summary-title" role="alert" tabindex="-1" data-module="govuk-error-summary">
                    <h2 class="govuk-error-summary__title" id="error-summary-title">
                        There is a problem
                    </h2>
                    <div class="govuk-error-summary__body">
                        <ul class="govuk-list govuk-error-summary__list">
                            @foreach (var error in Model.ErrorMessages)
                            {
                                <li>
                                    <a href="#@error.Field">@error.ErrorMessage</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>

            }

            <h1 class="govuk-heading-xl">Application overview</h1>

            @if (Model.Status == ApplicationSequenceStatus.Submitted)
            {
                <div class="das-apply-notification-summary govuk-!-margin-bottom-8">
                    <h2 class="govuk-heading-l">
                        Your application has been submitted
                    </h2>
                    <div class="govuk-body govuk-!-margin-bottom-0">
                        Once your application has been reviewed you'll hear from us by email.
                    </div>
                </div>
            }
            else
            {
                <ul class="govuk-list">
                    @foreach (var applicationSection in Model.Sections.OrderBy(s => s.SectionId))
                    {
                        <li>
                            <h2 id="@applicationSection.Id" class="govuk-heading-m govuk-!-margin-bottom-2">
                                @applicationSection.LinkTitle
                            </h2>
                            <span id="company-details-hint" class="govuk-hint">
                                @applicationSection.PagesComplete of @applicationSection.PagesActive questions completed
                            </span>
                            @if (Model.Status != ApplicationSequenceStatus.Submitted)
                            {
                                <a class="govuk-link" asp-action="Section" asp-controller="Application" asp-route-applicationId="@applicationSection.ApplicationId" asp-route-sequenceId="@applicationSection.SequenceId" asp-route-sectionId="@applicationSection.SectionId">
                                    Go to @applicationSection.LinkTitle.ToLower()
                                </a>
                            }
                        </li>
                        <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">
                    }
                </ul>

                @if (Model.Status != ApplicationSequenceStatus.Submitted)
                {
                    <form asp-action="Submit" asp-controller="Application" novalidate>
                        <input type="hidden" asp-for="ApplicationId" />
                        <input type="hidden" asp-for="SequenceId" />
                        <div class="govuk-form-group">
                            <button class="govuk-button" data-module="govuk-button" data-disable-on-submit="true">
                                Submit
                            </button>
                        </div>
                    </form>
                }
            }
        </div>
    </div>
</main>